name: 'Build, Scan, and Report Nginx'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-scan-and-report-nginx:
    name: Build, Scan, and Report Nginx
    runs-on: ubuntu-latest
    permissions:
      contents: write        
      security-events: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Nginx Docker image
        id: build-nginx
        uses: docker/build-push-action@v5
        with:
          context: ./nginx 
          push: false
          load: true
          tags: nginx-distroless-ci:latest

      # 1. Scan for Script (JSON Format)
      # دي الخطوة اللي السكربت محتاجها عشان يرسم الجدول
      - name: Run Trivy (JSON Output)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx-distroless-ci:latest'
          format: 'json' 
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          ignore-unfixed: false # عشان يظهر كل الثغرات

      # 2. Scan for Security Tab (SARIF Format)
      # دي عشان الـ Github Security Tab
      - name: Run Trivy (SARIF Output)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx-distroless-ci:latest'
          format: 'sarif' 
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          ignore-unfixed: false

      # 3. Generate The Fancy Table using your Script
      - name: Generate Job Summary Table
        run: |
          # تأكد إن السكربت موجود في المسار ده في الريبو بتاعك
          chmod +x .github/scripts/generate-report.sh
          ./.github/scripts/generate-report.sh trivy-results.json

      # 4. SBOM Section
      - name: Create SBOM Directory
        run: mkdir -p sbom-files

      - name: Generate SBOM for Nginx Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx-distroless-ci:latest'
          format: 'spdx-json'
          output: 'sbom-files/nginx-sbom.spdx.json'

      - name: Fix PURL Encoding (Replace + with %2B)
        run: |
          sed -i 's/%2B/%252B/g' sbom-files/nginx-sbom.spdx.json
          sed -i 's/+/%252B/g' sbom-files/nginx-sbom.spdx.json

      - name: Upload SBOM to GitHub Dependency Graph
        uses: advanced-security/spdx-dependency-submission-action@main
        with:
          filePath: sbom-files

      # 5. Upload Results to Security Tab
      - name: Upload Trivy Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'